
services:
  backend:
    build:
      context: ./backend/TodoList
      dockerfile: Dockerfile
    container_name: backend-dev
    ports:
      - "5128:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./backend/TodoList:/app                 # monta o código para hot reload
      - ~/.nuget/packages:/root/.nuget/packages    # cache do NuGet
    command: ["dotnet", "run"]
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "8080:8080"
    
    

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "MyStr0ng!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
